apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lets-encrypt-playground-cert
  namespace: seedwing
spec:
  commonName: playground.seedwing.io
  dnsNames:
  - playground.seedwing.io
  - monitoring.playground.seedwing.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 384
  secretName: letsencrypt-certificate
  secretTemplate:
    labels:
      cert-manager-created: "true"
  subject:
    organizations:
    - seedwing
