apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-deployment
  namespace: seedwing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployer-deployment
subjects:
- kind: ServiceAccount
  name: deployer
