apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-deployment
  namespace: seedwing
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - apply
  - update
  - create
  - patch
