name: deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New server tag to push'
        required: true
        type: string

permissions:
  contents: write # for creating a release

jobs:
  args:
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.getflags.outputs.commit }}
      imageref: ${{ steps.getflags.outputs.imageref }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: getflags
        run: |
          echo "commit=$(echo -n $GITHUB_SHA | head -c 8)" >> "$GITHUB_OUTPUT"
          echo "imageref=ghcr.io/seedwing-io/swio:${{inputs.tag}}" >> "$GITHUB_OUTPUT"
  tag:
    runs-on: ubuntu-22.04
    needs: args
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq
          chmod +x yq
      - name: Update tags
        run: |
          ./yq e -i ".spec.template.spec.containers[].image = '${{ needs.args.outputs.imageref }}'" deploy/server/deployment.yaml
      - name: Commit and tag
        run: |
          git commit deploy/server/deployment.yaml -m 'Update swio image'
          git tag v0.1.0-nightly.${{ needs.args.coutputs.commit }}
          git push --follow-tags
